title: Geopackage-so Documentation
description: Technical documentation published from GitHub

remote_theme: pages-themes/primer@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - README.md