title: Geopackage-so Documentation
description: Technical documentation published from GitHub
theme: jekyll-theme-primer

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - README.md
